# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
