# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='size',
            new_name='memory',
        ),
    ]
